### ISSUE TITLE
Crashes 1.18.2

### ISSUE THREAD

**Issue by NealSavage** [FoxShadew/Foxes#5]
Crashes on start. Fabric loader report below. Needs a proper 1.18.2 update. 

https://pastebin.com/tFMNNjRK

**Comment by FoxSamu** [comment]
Is it the only mod you have installed?
If not, please provide a list of the mods you're using (with versions)

**Comment by NealSavage** [comment]
I have a lot of mods, but it comes up only after I install the foxes mod, works if delete the fox mod, and happens again after reinstall. Has to be fox mod.
Here's the MultiMC console output https://pastebin.com/SLS1AjK3
And here's the logs https://pastebin.com/t9adq98Q

**Comment by FoxSamu** [comment]
Thank you

As odd as it may seem, it still doesn't have to be the foxes mod - it's an odd thing, if another mod messes something up before Foxes loads, it will appear as if Foxes breaks

I've known this issue but I've been off coding for the last months. If I get to it I'll see if I can reproduce the problem. Meanwhile, you can try if the problem persists if you launch the game with only Foxes (try with and without the Fabric API).

**Comment by NealSavage** [comment]
Okay, I'll make a new instance in MultiMC and test that for you.

**Comment by NealSavage** [comment]
Without Fabric API:
Result: Crashes.
Fabric loader logs: https://pastebin.com/DJ8g8Rzy
Logs: https://pastebin.com/LYcYp0EL
MultiMC Console Output: https://pastebin.com/81DvWwaU

With Fabric API:
Result: Crashes.
Fabric Loader Log: https://pastebin.com/tXeeL1tQ
Logs: https://pastebin.com/Cm4Leraq
MultiMC Console Output: https://pastebin.com/NKH4NUe8

**Comment by FoxSamu** [comment]
Thank you so much! That's useful information for me. I hope I can fix it soon.

**Comment by FoxSamu** [comment]
Releasing 1.3 which fixed the crash!
https://shadew.net/update/2022/05/07/foxes_1_18_2.html
